# অধ্যায় ১ঃ  নামপাই 

নামপাই হচ্ছে পাইথনের লিনিয়ার এলজেব্রার লাইব্রেরি। ডেটা সাইন্সের সকল সাইন্টিফিক ক্যালকুলেশন নামপাই ডেটা স্ট্রাকচার  ব্যবহার করে করা হয়। নামপাই এবং লিস্ট  অনেকটা একই রকম। চলুন লিস্ট থেকে নামপাই অ্যারে তৈরি করি।  

In [1]:
import numpy as np

In [2]:
python_list = [1, 2, 3]
print(python_list)
print(type(python_list))

[1, 2, 3]
<class 'list'>


In [3]:
numpy_array = np.array(python_list)

In [4]:
print(numpy_array)
print(type(numpy_array))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
multidim_array = [[1,2,3], [3,4,5], [5, 6, 7]]


In [6]:
print(multidim_array)
print(type(multidim_array))

[[1, 2, 3], [3, 4, 5], [5, 6, 7]]
<class 'list'>


In [7]:
metrix = np.array(multidim_array)

In [8]:
print(metrix)
print(type(metrix))

[[1 2 3]
 [3 4 5]
 [5 6 7]]
<class 'numpy.ndarray'>


# নামপাই বিল্ড ইন মেথড 

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## রেন্ডম নাম্বার দিয়ে নামপাই অ্যারে তৈরি 

In [15]:
np.random.rand(2)

array([0.49603699, 0.56636812])

In [16]:
np.random.rand(5,5)

array([[0.31159984, 0.23250545, 0.38675673, 0.00967968, 0.67578016],
       [0.93380998, 0.14000918, 0.98585961, 0.11214229, 0.64969464],
       [0.07622632, 0.07841992, 0.92293432, 0.30926641, 0.2235742 ],
       [0.94897151, 0.49932864, 0.13896988, 0.1612309 , 0.47255603],
       [0.97026191, 0.46847718, 0.10969575, 0.70064476, 0.40615168]])

In [17]:
np.random.randn(2)

array([1.41117416, 0.25100388])

In [18]:
np.random.randn(5,5)

array([[ 0.14231009, -0.89032232,  0.24093694,  0.66979945, -1.32070555],
       [ 1.86782802,  0.31785669, -0.56985765,  0.05582067, -0.7775443 ],
       [ 0.22236306, -0.63249634,  0.9372661 ,  0.02826342, -0.65799381],
       [ 1.31032083, -0.53172637,  1.10735237,  1.1924694 ,  0.19906979],
       [ 1.02841662,  0.39710131,  0.2886878 ,  0.83337553, -0.72857451]])

In [19]:
np.random.randint(1,100)

38

In [20]:
np.random.randint(1,100,10)

array([78, 70, 70, 68, 46, 64, 49, 10, 93, 24])


## নামপাই অ্যারে এট্রিবিউট এবং মেথড 

In [38]:
numpy_array = np.arange(25)
random_npArray = np.random.randint(0,50,10)

In [39]:
numpy_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
random_npArray

array([26,  2, 38, 13, 46, 16,  8, 31, 39, 44])

In [24]:
numpy_array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
random_npArray

array([26,  2, 38, 13, 46, 16,  8, 31, 39, 44])

In [43]:
random_npArray.max()

46

In [44]:
random_npArray.argmax()

4

In [45]:
random_npArray.min()

2

In [46]:
random_npArray.argmin()

1

## নামপাই shape ও dtype এট্রিবিউট


In [47]:
# Vector
numpy_array.shape

(25,)

In [49]:

numpy_array = numpy_array.reshape(1,25)

In [50]:
numpy_array.shape

(1, 25)

In [51]:
numpy_array.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [52]:
numpy_array.reshape(25,1).shape

(25, 1)

In [53]:
numpy_array.dtype

dtype('int64')


# নামপাই ইনডেক্সিং এবং সিলেকশন 

In [54]:
np_array = np.arange(0,11)

In [55]:
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np_array[7]

7

In [57]:
np_array[1: 7]

array([1, 2, 3, 4, 5, 6])

In [58]:
np_array[1: 7] = 10

In [59]:
np_array

array([ 0, 10, 10, 10, 10, 10, 10,  7,  8,  9, 10])