In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [6]:
cancer  = datasets.load_breast_cancer()

In [7]:
print(cancer.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [9]:
print(cancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [10]:
print(cancer.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [15]:

print(cancer.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [16]:
df = pd.DataFrame(cancer.data, columns=cancer.feature_names)

In [23]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  mean compactness  \
0          17.99         10.38          122.80     1001.0             0.12              0.28   
1          20.57         17.77          132.90     1326.0             0.08              0.08   
2          19.69         21.25          130.00     1203.0             0.11              0.16   
3          11.42         20.38           77.58      386.1             0.14              0.28   
4          20.29         14.34          135.10     1297.0             0.10              0.13   
..           ...           ...             ...        ...              ...               ...   
564        21.56         22.39          142.00     1479.0             0.11              0.12   
565        20.13         28.25          131.20     1261.0             0.10              0.10   
566        16.60         28.08          108.30      858.1             0.08              0.10   
567        20.60         29.33          140.10     1265.0             0.12              0.28   
568         7.76         24.54           47.92      181.0             0.05              0.04   

     mean concavity  mean concave points  mean symmetry  mean fractal dimension  ...  \
0              0.30                 0.15           0.24                    0.08  ...   
1              0.09                 0.07           0.18                    0.06  ...   
2              0.20                 0.13           0.21                    0.06  ...   
3              0.24                 0.11           0.26                    0.10  ...   
4              0.20                 0.10           0.18                    0.06  ...   
..              ...                  ...            ...                     ...  ...   
564            0.24                 0.14           0.17                    0.06  ...   
565            0.14                 0.10           0.18                    0.06  ...   
566            0.09                 0.05           0.16                    0.06  ...   
567            0.35                 0.15           0.24                    0.07  ...   
568            0.00                 0.00           0.16                    0.06  ...   

     worst radius  worst texture  worst perimeter  worst area  worst smoothness  \
0           25.38          17.33           184.60      2019.0              0.16   
1           24.99          23.41           158.80      1956.0              0.12   
2           23.57          25.53           152.50      1709.0              0.14   
3           14.91          26.50            98.87       567.7              0.21   
4           22.54          16.67           152.20      1575.0              0.14   
..            ...            ...              ...         ...               ...   
564         25.45          26.40           166.10      2027.0              0.14   
565         23.69          38.25           155.00      1731.0              0.12   
566         18.98          34.12           126.70      1124.0              0.11   
567         25.74          39.42           184.60      1821.0              0.17   
568          9.46          30.37            59.16       268.6              0.09   

     worst compactness  worst concavity  worst concave points  worst symmetry  \
0                 0.67             0.71                  0.27            0.46   
1                 0.19             0.24                  0.19            0.28   
2                 0.42             0.45                  0.24            0.36   
3                 0.87             0.69                  0.26            0.66   
4                 0.20             0.40                  0.16            0.24   
..                 ...              ...                   ...             ...   
564               0.21             0.41                  0.22            0.21   
565               0.19             0.32                  0.16            0.26   
566               0.31             0.34                  0.14        

In [21]:
df.describe()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  mean compactness  \
count       569.00        569.00          569.00     569.00           569.00            569.00   
mean         14.13         19.29           91.97     654.89             0.10              0.10   
std           3.52          4.30           24.30     351.91             0.01              0.05   
min           6.98          9.71           43.79     143.50             0.05              0.02   
25%          11.70         16.17           75.17     420.30             0.09              0.06   
50%          13.37         18.84           86.24     551.10             0.10              0.09   
75%          15.78         21.80          104.10     782.70             0.11              0.13   
max          28.11         39.28          188.50    2501.00             0.16              0.35   

       mean concavity  mean concave points  mean symmetry  mean fractal dimension  ...  \
count          569.00               569.00         569.00                5.69e+02  ...   
mean             0.09                 0.05           0.18                6.28e-02  ...   
std              0.08                 0.04           0.03                7.06e-03  ...   
min              0.00                 0.00           0.11                5.00e-02  ...   
25%              0.03                 0.02           0.16                5.77e-02  ...   
50%              0.06                 0.03           0.18                6.15e-02  ...   
75%              0.13                 0.07           0.20                6.61e-02  ...   
max              0.43                 0.20           0.30                9.74e-02  ...   

       worst radius  worst texture  worst perimeter  worst area  worst smoothness  \
count        569.00         569.00           569.00      569.00            569.00   
mean          16.27          25.68           107.26      880.58              0.13   
std            4.83           6.15            33.60      569.36              0.02   
min            7.93          12.02            50.41      185.20              0.07   
25%           13.01          21.08            84.11      515.30              0.12   
50%           14.97          25.41            97.66      686.50              0.13   
75%           18.79          29.72           125.40     1084.00              0.15   
max           36.04          49.54           251.20     4254.00              0.22   

       worst compactness  worst concavity  worst concave points  worst symmetry  \
count             569.00           569.00                569.00          569.00   
mean                0.25             0.27                  0.11            0.29   
std                 0.16             0.21                  0.07            0.06   
min                 0.03             0.00                  0.00            0.16   
25%                 0.15             0.11                  0.06            0.25   
50%                 0.21             0.23                  0.10            0.28   
75%                 0.34             0.38                  0.16            0.32   
max                 1.06             1.25                  0.29            0.66   

       worst fractal dimension  
count                   569.00  
mean                      0.08  
std                       0.02  
min                       0.06  
25%                       0.07  
50%                       0.08  
75%                       0.09  
max                       0.21  

[8 rows x 30 columns]

In [19]:
df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry      

In [26]:
print(df.corr())

                         mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
mean radius                 1.00e+00      3.24e-01        9.98e-01   9.87e-01             0.17   
mean texture                3.24e-01      1.00e+00        3.30e-01   3.21e-01            -0.02   
mean perimeter              9.98e-01      3.30e-01        1.00e+00   9.87e-01             0.21   
mean area                   9.87e-01      3.21e-01        9.87e-01   1.00e+00             0.18   
mean smoothness             1.71e-01     -2.34e-02        2.07e-01   1.77e-01             1.00   
mean compactness            5.06e-01      2.37e-01        5.57e-01   4.99e-01             0.66   
mean concavity              6.77e-01      3.02e-01        7.16e-01   6.86e-01             0.52   
mean concave points         8.23e-01      2.93e-01        8.51e-01   8.23e-01             0.55   
mean symmetry               1.48e-01      7.14e-02        1.83e-01   1.51e-01             0.56   
mean fractal dimensi